### ISSUE TITLE
Is there a way to show all available commands when the user hasn't typed anything yet?

### ISSUE THREAD

**Issue by ashleydavis** [1egoman/fuzzy-picker#15]
Hi, great component! 

Just wondering if there is any way that I can show all commands before the user has typed anything?

The way VS code does it:

![vs command palette](https://user-images.githubusercontent.com/625126/45458002-f87e2880-b734-11e8-8558-8e152fe759b8.png)

Thanks so much!
Ash

**Comment by 1egoman** [comment]
Hmm, no, not by default.

However, you should be able to subclass `FuzzyPicker` and override the `getInitialItems` method to return the initial set of items to render when the popup is opened - see https://github.com/1egoman/fuzzy-picker/blob/master/src/fuzzy-picker.js#L88. In addition, some logic may be required (depending on hte behavior that you need) to show all items on further searches. If you end up going this route and would be willing contribute this back (in a fashion that this option would be configurable) I'd gladly accept a pull request for it!

**Comment by ashleydavis** [comment]
I'd love to contribute actually. I have a few things I'd like to add, I'll keep each change simple and in separate pull requests so that you can consider them independently.

Do you have any coding style or unit tests I need to know about?

**Comment by 1egoman** [comment]
> I'd love to contribute actually.

Sweet!

> Do you have any coding style or unit tests I need to know about?

There's a contributing document that talks about both of those: https://github.com/1egoman/fuzzy-picker/blob/master/CONTRIBUTING.md. Let me know if you have any specific comments and I'd be happy to address them.

**Comment by ashleydavis** [comment]
Cheers, just getting started. I forked, cloned and did the`npm install`.

But I get the following error relating to the 'hoek' module. Any idea what this is all about?

```

> npm install                                                                                                                                                                                                                                  
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-UWbihkV/AzBgZL5Ul+jbsMPTIIM= integrity checksum failed when using sha1: wanted sha1-UWbihkV/AzBgZL5Ul+jbsMPTIIM= but got sha512-yJ
VQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==. (11423 bytes)                                                                                                                                           
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.                                                                                                                        
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=3.7.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit
 to get more info.                                                                                                                                                                                                                             
                                                                                                                                                                                                                                               
> node-sass@4.8.3 install C:\projects\github\fuzzy-picker\node_modules\node-sass                                                                                                                                                               
> node scripts/install.js                                                                                                                                                                                                                      
                                                                                                                                                                                                                                               
module.js:540                                                                                                                                                                                                                                  
    throw err;                                                                                                                                                                                                                                 
    ^                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                               
Error: Cannot find module 'hoek'                                                                                                                                                                                                               
    at Function.Module._resolveFilename (module.js:538:15)                                                                                                                                                                                     
    at Function.Module._load (module.js:468:25)                                                                                                                                                                                                
    at Module.require (module.js:587:17)                                                                                                                                                                                                       
    at require (internal/module.js:11:18)                                                                                                                                                                                                      
    at Object.<anonymous> (C:\projects\github\fuzzy-picker\node_modules\boom\lib\index.js:4:12)                                                                                                                                                
    at Module._compile (module.js:643:30)                                                                                                                                                                                                      
    at Object.Module._extensions..js (module.js:654:10)                                                                                                                                                                                        
    at Module.load (module.js:556:32)                                                                                                                                                                                                          
    at tryModuleLoad (module.js:499:12)                                                                                                                                                                                                        
    at Function.Module._load (module.js:491:3)                                                                                                                                                                                                 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):                                                                                                                                                        
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})                                                                              
                                                                                                                                                                                                                                               
npm ERR! code ELIFECYCLE                                                                                                                                                                                                                       
npm ERR! errno 1                                                                                                                                                                                                                               
npm ERR! node-sass@4.8.3 install: `node scripts/install.js`                                                                                                                                                                                    
npm ERR! Exit status 1                                                                                                                                                                                                                         
npm ERR!                                                                                                                                                                                                                                       
npm ERR! Failed at the node-sass@4.8.3 install script.                                                                                                                                                                                         
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                                                                                             
                                                                                                                                                                                                                                               
npm ERR! A complete log of this run can be found in:                                                                                                                                                                                           
npm ERR!     C:\Users\ash\AppData\Roaming\npm-cache\_logs\2018-09-13T05_39_05_838Z-debug.log                                                                                                                                                   
                          
```

**Comment by ashleydavis** [comment]
I'm working on Windows, which seems pertinent.

**Comment by ashleydavis** [comment]
Ok, problem solved.

I'm making a slight tweak to your contribution guide (what I need to get started).

I'll make a pull request so we can test the integration process!

**Comment by 1egoman** [comment]
Ok, sweet! This process may be a bit rough around the edges, it's been a while since I did any real development on this project. It seems like in general it's gone relatively well so far! I merged https://github.com/1egoman/fuzzy-picker/pull/16, and I also pushed a commit to change the versions of node that travis ci builds with as some dependencies have updated to no longer support node 5 and 6 (travis now builds with node 8 and 10). That will hopefully fix up the ci process.

**Comment by ashleydavis** [comment]
Yeah it's definitely a good start for what I need.

One issue I have is that it won't dismiss when I hit enter. Should that already work?

**Comment by 1egoman** [comment]
It should if an item is selected - ie, in https://1egoman.github.io/fuzzy-picker/ or with `gulp example` locally, if I press `/` to open, then type `lorem` and press enter, it selects the given item and the picker closes. Are you unable to replicate this behavior?

**Comment by ashleydavis** [comment]
Not currently, but it's probably my fault. Pretty tired at the moment and still hacking away.

**Comment by ashleydavis** [comment]
These are things I want to add to it:
- Display all items (make this opt in for backward compatibility).

Potentially later:
- Show 1-3 recently used commands at the top of the list.
- Be able to switch modes, for example Visual Studio Code has one command palette but you can dynamically switch it between commands and the list of open files.

**Comment by ashleydavis** [comment]
BTW this is the app that I'm building:

[http://www.data-forge-notebook.com/](http://www.data-forge-notebook.com/)

**Comment by 1egoman** [comment]
That looks pretty cool!

**Comment by ashleydavis** [comment]
Also I'd like to show hotkeys for the commands in the fuzzy picker. But that's low priority.

**Comment by ashleydavis** [comment]
It also needs a dark theme ;)

**Comment by 1egoman** [comment]
Also, all those ideas sound great! I'd say that it'd be nice if all of them could be enabled or disabled such that someone could pick how minimal or extensible of a picker they'd like. Ha, and I agree on the dark theme too, it's something that I tend to do in applications as well.
